/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgamal;

import java.math.BigInteger;

/**
 *
 * @author LuisEduardoLeyvaHerrera
 */
public class Usuario1 extends javax.swing.JFrame {
    // A es la clave pública del Usuario1 generada por el algoritmo ElGamal
    private BigInteger A;
    // Se crea una instancia de Usuario2
    private Usuario2 u2 = new Usuario2();
    // mensajeDes es el mensaje descifrado que se muestra en la interfaz de Usuario1
    private String mensajeDes;
    // Se crea una instancia de AlgoritmoElGamal para generar claves y descifrar mensajes
    private AlgoritmoElGamal aeg = new AlgoritmoElGamal();
    /**
     * Creates new form Usuario1
     */
    public Usuario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAMensaje = new javax.swing.JTextArea();
        jBtnEnviar = new javax.swing.JButton();
        jBtnDescifrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTAMensaje.setEditable(false);
        jTAMensaje.setColumns(20);
        jTAMensaje.setRows(5);
        jScrollPane1.setViewportView(jTAMensaje);

        jBtnEnviar.setText("Enviar");
        jBtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });

        jBtnDescifrar.setText("Descifrar");
        jBtnDescifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDescifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnDescifrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEnviar)
                    .addComponent(jBtnDescifrar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
      // Este método se llama cuando se hace clic en el botón "Enviar" en la ventana principal
                                           
  // Obtiene el valor de la clave pública A generada por el algoritmo AEG
  A = aeg.getA();
  // Hace visible la ventana de chat u2
  u2.setVisible(true);
  // Agrega la clave pública A al campo de texto JTAMensajes de la ventana de chat u2
  u2.JTAMensajes.append(A.toString());
  // Oculta la ventana principal
  this.setVisible(false);

    }//GEN-LAST:event_jBtnEnviarActionPerformed

    private void jBtnDescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDescifrarActionPerformed
 // Este método se llama cuando se hace clic en el botón "Descifrar" en la ventana de chat u2
                  
  // Obtiene el mensaje cifrado ingresado por el usuario en el campo de texto jTAMensaje de la ventana de chat u2
  mensajeDes = jTAMensaje.getText();
  // Descifra el mensaje utilizando el algoritmo AEG y lo guarda en la variable mensajeDes
  mensajeDes = aeg.bigDecrypt(mensajeDes);
  // Agrega el mensaje descifrado al campo de texto jTAMensaje de la ventana de chat u2
  jTAMensaje.append(mensajeDes);

    }//GEN-LAST:event_jBtnDescifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnDescifrar;
    private javax.swing.JButton jBtnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTAMensaje;
    // End of variables declaration//GEN-END:variables
}
